---
- name: Prepare all nodes
  hosts: k8s_cluster
  roles:
    - common
    - container_runtime
    - kubernetes
    - os_update

- name: Initialize Control Plane
  hosts: control_plane
  roles:
    - control_plane

- name: Join Worker Nodes
  hosts: workers
  roles:
    - worker
